#! /bin/sh

bspc config border_width        0
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Google-chrome desktop=^1 floating=on private=on 
bspc rule -a urxvt floating=on
bspc rule -a libreoffice floating=on private=on
bspc rule -a Display floating=on
